services:
  node-app:
    build: . # so the . meand current file which is going to be built and it will run the Docker file
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000